language: generic

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

cache:
  directories:
    - $HOME/.dotnet

before_install:
  - if [ "$OS" = "linux" ]; then sudo apt-get install libunwind8 libicu-dev libcurl4-openssl-dev; fi

before_script:
  - if [ "$OS" = "linux" ]; then pyenv global 3.6.3; alias python=python3; fi
  - export PYTHONPATH=.
  - export CLARIFAI_APP_ID="$(python scripts/app_and_key_for_tests.py --create-app csharp-travis)"
  - export CLARIFAI_API_KEY="$(python scripts/app_and_key_for_tests.py --create-key ${CLARIFAI_APP_ID})"
  - python scripts/app_and_key_for_tests.py --create-workflow ${CLARIFAI_API_KEY}

script:
  - wget https://dot.net/v1/dotnet-install.sh && chmod +x dotnet-install.sh
  - ./dotnet-install.sh --channel $DOTNET_CORE_VERSION --version latest --install-dir $HOME/.dotnet
  - $HOME/.dotnet/dotnet restore
  - $HOME/.dotnet/dotnet test Clarifai.IntegrationTests/Clarifai.IntegrationTests.csproj
  - $HOME/.dotnet/dotnet test Clarifai.UnitTests/Clarifai.UnitTests.csproj

after_script:
  - export PYTHONPATH=.
  - python scripts/app_and_key_for_tests.py --delete-app $CLARIFAI_APP_ID

before_cache:
  - rm -rf $HOME/.dotnet/optimizationdata

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - OS=linux
        - DOTNET_CORE_VERSION=2.0
    - os: linux
      dist: trusty
      env:
        - OS=linux
        - DOTNET_CORE_VERSION=LTS
    - os: linux
      dist: trusty
      env:
        - OS=linux
        - DOTNET_CORE_VERSION=Current
    - os: osx
      osx_image: xcode9.3
      env:
        - OS=osx93
        - DOTNET_CORE_VERSION=LTS
    - os: osx
      python: "3.6"
      osx_image: xcode9.3
      env:
        - OS=osx93
        - DOTNET_CORE_VERSION=Current
    - os: osx
      python: "3.6"
      osx_image: xcode9.2
      env:
        - OS=osx
        - DOTNET_CORE_VERSION=LTS
    - os: osx
      python: "3.6"
      osx_image: xcode9.2
      env:
        - OS=osx
        - DOTNET_CORE_VERSION=Current

deploy:
  - provider: script
    script:
      - chmod +x ./deploy.sh && ./deploy.sh
    skip_cleanup: true
    on:
      condition: "$OS == osx && $DOTNET_CORE_VERSION == Current"
      tags: true
      repo: Clarifai/clarifai-csharp
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUB_TOKEN
    file_glob: true
    file:
      - Clarifai/bin/Release/Clarifai.*.nupkg
      - Clarifai/bin/Release/netstandard1.3/Clarifai.dll
    on:
      condition: "$OS == osx && $DOTNET_CORE_VERSION == Current"
      tags: true
      repo: Clarifai/clarifai-csharp
