version: '1.0.{build}'
image: Visual Studio 2017

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

before_build:
  # Display .NET Core version
  - cmd: dotnet --version

build_script:
  - cmd: dotnet restore

test_script:
  - cmd: dotnet test Clarifai.IntegrationTests/Clarifai.IntegrationTests.csproj
  - cmd: dotnet test Clarifai.UnitTests/Clarifai.UnitTests.csproj

