// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/clarifai/api/concept_graph.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Clarifai.Internal.GRPC {

  /// <summary>Holder for reflection information generated from proto/clarifai/api/concept_graph.proto</summary>
  public static partial class ConceptGraphReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/clarifai/api/concept_graph.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConceptGraphReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZwcm90by9jbGFyaWZhaS9hcGkvY29uY2VwdF9ncmFwaC5wcm90bxIMY2xh",
            "cmlmYWkuYXBpGh9wcm90by9jbGFyaWZhaS9hcGkvY29tbW9uLnByb3RvGilw",
            "cm90by9jbGFyaWZhaS9hcGkvdXRpbHMvZXh0ZW5zaW9ucy5wcm90byKVAQob",
            "TGlzdENvbmNlcHRSZWxhdGlvbnNSZXF1ZXN0Ei8KC3VzZXJfYXBwX2lkGAEg",
            "ASgLMhouY2xhcmlmYWkuYXBpLlVzZXJBcHBJRFNldBISCgpjb25jZXB0X2lk",
            "GAIgASgJEhEKCXByZWRpY2F0ZRgDIAEoCRIMCgRwYWdlGAQgASgNEhAKCHBl",
            "cl9wYWdlGAUgASgNQloKG2NsYXJpZmFpMi5pbnRlcm5hbC5ncnBjLmFwaVoD",
            "YXBpogIEQ0FJUKoCFkNsYXJpZmFpLkludGVybmFsLkdSUEPCAgFfygIRQ2xh",
            "cmlmYWlcSW50ZXJuYWxiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Clarifai.Internal.GRPC.CommonReflection.Descriptor, global::Clarifai.Internal.GRPC.Utils.ExtensionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Clarifai.Internal.GRPC.ListConceptRelationsRequest), global::Clarifai.Internal.GRPC.ListConceptRelationsRequest.Parser, new[]{ "UserAppId", "ConceptId", "Predicate", "Page", "PerPage" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ListConceptRelationsRequest : pb::IMessage<ListConceptRelationsRequest> {
    private static readonly pb::MessageParser<ListConceptRelationsRequest> _parser = new pb::MessageParser<ListConceptRelationsRequest>(() => new ListConceptRelationsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ListConceptRelationsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Clarifai.Internal.GRPC.ConceptGraphReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListConceptRelationsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListConceptRelationsRequest(ListConceptRelationsRequest other) : this() {
      UserAppId = other.userAppId_ != null ? other.UserAppId.Clone() : null;
      conceptId_ = other.conceptId_;
      predicate_ = other.predicate_;
      page_ = other.page_;
      perPage_ = other.perPage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListConceptRelationsRequest Clone() {
      return new ListConceptRelationsRequest(this);
    }

    /// <summary>Field number for the "user_app_id" field.</summary>
    public const int UserAppIdFieldNumber = 1;
    private global::Clarifai.Internal.GRPC.UserAppIDSet userAppId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Clarifai.Internal.GRPC.UserAppIDSet UserAppId {
      get { return userAppId_; }
      set {
        userAppId_ = value;
      }
    }

    /// <summary>Field number for the "concept_id" field.</summary>
    public const int ConceptIdFieldNumber = 2;
    private string conceptId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ConceptId {
      get { return conceptId_; }
      set {
        conceptId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "predicate" field.</summary>
    public const int PredicateFieldNumber = 3;
    private string predicate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Predicate {
      get { return predicate_; }
      set {
        predicate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "page" field.</summary>
    public const int PageFieldNumber = 4;
    private uint page_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Page {
      get { return page_; }
      set {
        page_ = value;
      }
    }

    /// <summary>Field number for the "per_page" field.</summary>
    public const int PerPageFieldNumber = 5;
    private uint perPage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PerPage {
      get { return perPage_; }
      set {
        perPage_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ListConceptRelationsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ListConceptRelationsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UserAppId, other.UserAppId)) return false;
      if (ConceptId != other.ConceptId) return false;
      if (Predicate != other.Predicate) return false;
      if (Page != other.Page) return false;
      if (PerPage != other.PerPage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (userAppId_ != null) hash ^= UserAppId.GetHashCode();
      if (ConceptId.Length != 0) hash ^= ConceptId.GetHashCode();
      if (Predicate.Length != 0) hash ^= Predicate.GetHashCode();
      if (Page != 0) hash ^= Page.GetHashCode();
      if (PerPage != 0) hash ^= PerPage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (userAppId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UserAppId);
      }
      if (ConceptId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ConceptId);
      }
      if (Predicate.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Predicate);
      }
      if (Page != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Page);
      }
      if (PerPage != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(PerPage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (userAppId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserAppId);
      }
      if (ConceptId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConceptId);
      }
      if (Predicate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Predicate);
      }
      if (Page != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Page);
      }
      if (PerPage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PerPage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ListConceptRelationsRequest other) {
      if (other == null) {
        return;
      }
      if (other.userAppId_ != null) {
        if (userAppId_ == null) {
          userAppId_ = new global::Clarifai.Internal.GRPC.UserAppIDSet();
        }
        UserAppId.MergeFrom(other.UserAppId);
      }
      if (other.ConceptId.Length != 0) {
        ConceptId = other.ConceptId;
      }
      if (other.Predicate.Length != 0) {
        Predicate = other.Predicate;
      }
      if (other.Page != 0) {
        Page = other.Page;
      }
      if (other.PerPage != 0) {
        PerPage = other.PerPage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (userAppId_ == null) {
              userAppId_ = new global::Clarifai.Internal.GRPC.UserAppIDSet();
            }
            input.ReadMessage(userAppId_);
            break;
          }
          case 18: {
            ConceptId = input.ReadString();
            break;
          }
          case 26: {
            Predicate = input.ReadString();
            break;
          }
          case 32: {
            Page = input.ReadUInt32();
            break;
          }
          case 40: {
            PerPage = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
