// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/google/api/http.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Api {

  /// <summary>Holder for reflection information generated from proto/google/api/http.proto</summary>
  public static partial class HttpReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/google/api/http.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HttpReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtwcm90by9nb29nbGUvYXBpL2h0dHAucHJvdG8SCmdvb2dsZS5hcGkiKwoE",
            "SHR0cBIjCgVydWxlcxgBIAMoCzIULmdvb2dsZS5hcGkuSHR0cFJ1bGUi6gEK",
            "CEh0dHBSdWxlEhAKCHNlbGVjdG9yGAEgASgJEg0KA2dldBgCIAEoCUgAEg0K",
            "A3B1dBgDIAEoCUgAEg4KBHBvc3QYBCABKAlIABIQCgZkZWxldGUYBSABKAlI",
            "ABIPCgVwYXRjaBgGIAEoCUgAEi8KBmN1c3RvbRgIIAEoCzIdLmdvb2dsZS5h",
            "cGkuQ3VzdG9tSHR0cFBhdHRlcm5IABIMCgRib2R5GAcgASgJEjEKE2FkZGl0",
            "aW9uYWxfYmluZGluZ3MYCyADKAsyFC5nb29nbGUuYXBpLkh0dHBSdWxlQgkK",
            "B3BhdHRlcm4iLwoRQ3VzdG9tSHR0cFBhdHRlcm4SDAoEa2luZBgBIAEoCRIM",
            "CgRwYXRoGAIgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Api.Http), global::Google.Api.Http.Parser, new[]{ "Rules" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Api.HttpRule), global::Google.Api.HttpRule.Parser, new[]{ "Selector", "Get", "Put", "Post", "Delete", "Patch", "Custom", "Body", "AdditionalBindings" }, new[]{ "Pattern" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Api.CustomHttpPattern), global::Google.Api.CustomHttpPattern.Parser, new[]{ "Kind", "Path" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Http : pb::IMessage<Http> {
    private static readonly pb::MessageParser<Http> _parser = new pb::MessageParser<Http>(() => new Http());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Http> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Api.HttpReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Http() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Http(Http other) : this() {
      rules_ = other.rules_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Http Clone() {
      return new Http(this);
    }

    /// <summary>Field number for the "rules" field.</summary>
    public const int RulesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Google.Api.HttpRule> _repeated_rules_codec
        = pb::FieldCodec.ForMessage(10, global::Google.Api.HttpRule.Parser);
    private readonly pbc::RepeatedField<global::Google.Api.HttpRule> rules_ = new pbc::RepeatedField<global::Google.Api.HttpRule>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Api.HttpRule> Rules {
      get { return rules_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Http);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Http other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!rules_.Equals(other.rules_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= rules_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      rules_.WriteTo(output, _repeated_rules_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += rules_.CalculateSize(_repeated_rules_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Http other) {
      if (other == null) {
        return;
      }
      rules_.Add(other.rules_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            rules_.AddEntriesFrom(input, _repeated_rules_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class HttpRule : pb::IMessage<HttpRule> {
    private static readonly pb::MessageParser<HttpRule> _parser = new pb::MessageParser<HttpRule>(() => new HttpRule());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HttpRule> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Api.HttpReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HttpRule() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HttpRule(HttpRule other) : this() {
      selector_ = other.selector_;
      body_ = other.body_;
      additionalBindings_ = other.additionalBindings_.Clone();
      switch (other.PatternCase) {
        case PatternOneofCase.Get:
          Get = other.Get;
          break;
        case PatternOneofCase.Put:
          Put = other.Put;
          break;
        case PatternOneofCase.Post:
          Post = other.Post;
          break;
        case PatternOneofCase.Delete:
          Delete = other.Delete;
          break;
        case PatternOneofCase.Patch:
          Patch = other.Patch;
          break;
        case PatternOneofCase.Custom:
          Custom = other.Custom.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HttpRule Clone() {
      return new HttpRule(this);
    }

    /// <summary>Field number for the "selector" field.</summary>
    public const int SelectorFieldNumber = 1;
    private string selector_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Selector {
      get { return selector_; }
      set {
        selector_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "get" field.</summary>
    public const int GetFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Get {
      get { return patternCase_ == PatternOneofCase.Get ? (string) pattern_ : ""; }
      set {
        pattern_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        patternCase_ = PatternOneofCase.Get;
      }
    }

    /// <summary>Field number for the "put" field.</summary>
    public const int PutFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Put {
      get { return patternCase_ == PatternOneofCase.Put ? (string) pattern_ : ""; }
      set {
        pattern_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        patternCase_ = PatternOneofCase.Put;
      }
    }

    /// <summary>Field number for the "post" field.</summary>
    public const int PostFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Post {
      get { return patternCase_ == PatternOneofCase.Post ? (string) pattern_ : ""; }
      set {
        pattern_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        patternCase_ = PatternOneofCase.Post;
      }
    }

    /// <summary>Field number for the "delete" field.</summary>
    public const int DeleteFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Delete {
      get { return patternCase_ == PatternOneofCase.Delete ? (string) pattern_ : ""; }
      set {
        pattern_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        patternCase_ = PatternOneofCase.Delete;
      }
    }

    /// <summary>Field number for the "patch" field.</summary>
    public const int PatchFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Patch {
      get { return patternCase_ == PatternOneofCase.Patch ? (string) pattern_ : ""; }
      set {
        pattern_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        patternCase_ = PatternOneofCase.Patch;
      }
    }

    /// <summary>Field number for the "custom" field.</summary>
    public const int CustomFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Api.CustomHttpPattern Custom {
      get { return patternCase_ == PatternOneofCase.Custom ? (global::Google.Api.CustomHttpPattern) pattern_ : null; }
      set {
        pattern_ = value;
        patternCase_ = value == null ? PatternOneofCase.None : PatternOneofCase.Custom;
      }
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 7;
    private string body_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Body {
      get { return body_; }
      set {
        body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "additional_bindings" field.</summary>
    public const int AdditionalBindingsFieldNumber = 11;
    private static readonly pb::FieldCodec<global::Google.Api.HttpRule> _repeated_additionalBindings_codec
        = pb::FieldCodec.ForMessage(90, global::Google.Api.HttpRule.Parser);
    private readonly pbc::RepeatedField<global::Google.Api.HttpRule> additionalBindings_ = new pbc::RepeatedField<global::Google.Api.HttpRule>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Api.HttpRule> AdditionalBindings {
      get { return additionalBindings_; }
    }

    private object pattern_;
    /// <summary>Enum of possible cases for the "pattern" oneof.</summary>
    public enum PatternOneofCase {
      None = 0,
      Get = 2,
      Put = 3,
      Post = 4,
      Delete = 5,
      Patch = 6,
      Custom = 8,
    }
    private PatternOneofCase patternCase_ = PatternOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PatternOneofCase PatternCase {
      get { return patternCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearPattern() {
      patternCase_ = PatternOneofCase.None;
      pattern_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HttpRule);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HttpRule other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Selector != other.Selector) return false;
      if (Get != other.Get) return false;
      if (Put != other.Put) return false;
      if (Post != other.Post) return false;
      if (Delete != other.Delete) return false;
      if (Patch != other.Patch) return false;
      if (!object.Equals(Custom, other.Custom)) return false;
      if (Body != other.Body) return false;
      if(!additionalBindings_.Equals(other.additionalBindings_)) return false;
      if (PatternCase != other.PatternCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Selector.Length != 0) hash ^= Selector.GetHashCode();
      if (patternCase_ == PatternOneofCase.Get) hash ^= Get.GetHashCode();
      if (patternCase_ == PatternOneofCase.Put) hash ^= Put.GetHashCode();
      if (patternCase_ == PatternOneofCase.Post) hash ^= Post.GetHashCode();
      if (patternCase_ == PatternOneofCase.Delete) hash ^= Delete.GetHashCode();
      if (patternCase_ == PatternOneofCase.Patch) hash ^= Patch.GetHashCode();
      if (patternCase_ == PatternOneofCase.Custom) hash ^= Custom.GetHashCode();
      if (Body.Length != 0) hash ^= Body.GetHashCode();
      hash ^= additionalBindings_.GetHashCode();
      hash ^= (int) patternCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Selector.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Selector);
      }
      if (patternCase_ == PatternOneofCase.Get) {
        output.WriteRawTag(18);
        output.WriteString(Get);
      }
      if (patternCase_ == PatternOneofCase.Put) {
        output.WriteRawTag(26);
        output.WriteString(Put);
      }
      if (patternCase_ == PatternOneofCase.Post) {
        output.WriteRawTag(34);
        output.WriteString(Post);
      }
      if (patternCase_ == PatternOneofCase.Delete) {
        output.WriteRawTag(42);
        output.WriteString(Delete);
      }
      if (patternCase_ == PatternOneofCase.Patch) {
        output.WriteRawTag(50);
        output.WriteString(Patch);
      }
      if (Body.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Body);
      }
      if (patternCase_ == PatternOneofCase.Custom) {
        output.WriteRawTag(66);
        output.WriteMessage(Custom);
      }
      additionalBindings_.WriteTo(output, _repeated_additionalBindings_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Selector.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Selector);
      }
      if (patternCase_ == PatternOneofCase.Get) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Get);
      }
      if (patternCase_ == PatternOneofCase.Put) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Put);
      }
      if (patternCase_ == PatternOneofCase.Post) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Post);
      }
      if (patternCase_ == PatternOneofCase.Delete) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Delete);
      }
      if (patternCase_ == PatternOneofCase.Patch) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Patch);
      }
      if (patternCase_ == PatternOneofCase.Custom) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Custom);
      }
      if (Body.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Body);
      }
      size += additionalBindings_.CalculateSize(_repeated_additionalBindings_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HttpRule other) {
      if (other == null) {
        return;
      }
      if (other.Selector.Length != 0) {
        Selector = other.Selector;
      }
      if (other.Body.Length != 0) {
        Body = other.Body;
      }
      additionalBindings_.Add(other.additionalBindings_);
      switch (other.PatternCase) {
        case PatternOneofCase.Get:
          Get = other.Get;
          break;
        case PatternOneofCase.Put:
          Put = other.Put;
          break;
        case PatternOneofCase.Post:
          Post = other.Post;
          break;
        case PatternOneofCase.Delete:
          Delete = other.Delete;
          break;
        case PatternOneofCase.Patch:
          Patch = other.Patch;
          break;
        case PatternOneofCase.Custom:
          if (Custom == null) {
            Custom = new global::Google.Api.CustomHttpPattern();
          }
          Custom.MergeFrom(other.Custom);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Selector = input.ReadString();
            break;
          }
          case 18: {
            Get = input.ReadString();
            break;
          }
          case 26: {
            Put = input.ReadString();
            break;
          }
          case 34: {
            Post = input.ReadString();
            break;
          }
          case 42: {
            Delete = input.ReadString();
            break;
          }
          case 50: {
            Patch = input.ReadString();
            break;
          }
          case 58: {
            Body = input.ReadString();
            break;
          }
          case 66: {
            global::Google.Api.CustomHttpPattern subBuilder = new global::Google.Api.CustomHttpPattern();
            if (patternCase_ == PatternOneofCase.Custom) {
              subBuilder.MergeFrom(Custom);
            }
            input.ReadMessage(subBuilder);
            Custom = subBuilder;
            break;
          }
          case 90: {
            additionalBindings_.AddEntriesFrom(input, _repeated_additionalBindings_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class CustomHttpPattern : pb::IMessage<CustomHttpPattern> {
    private static readonly pb::MessageParser<CustomHttpPattern> _parser = new pb::MessageParser<CustomHttpPattern>(() => new CustomHttpPattern());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CustomHttpPattern> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Api.HttpReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CustomHttpPattern() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CustomHttpPattern(CustomHttpPattern other) : this() {
      kind_ = other.kind_;
      path_ = other.path_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CustomHttpPattern Clone() {
      return new CustomHttpPattern(this);
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 1;
    private string kind_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Kind {
      get { return kind_; }
      set {
        kind_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 2;
    private string path_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Path {
      get { return path_; }
      set {
        path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CustomHttpPattern);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CustomHttpPattern other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Kind != other.Kind) return false;
      if (Path != other.Path) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Kind.Length != 0) hash ^= Kind.GetHashCode();
      if (Path.Length != 0) hash ^= Path.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Kind.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Kind);
      }
      if (Path.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Path);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Kind.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Kind);
      }
      if (Path.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CustomHttpPattern other) {
      if (other == null) {
        return;
      }
      if (other.Kind.Length != 0) {
        Kind = other.Kind;
      }
      if (other.Path.Length != 0) {
        Path = other.Path;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Kind = input.ReadString();
            break;
          }
          case 18: {
            Path = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
