// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/clarifai/api/image.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Clarifai.Internal.GRPC {

  /// <summary>Holder for reflection information generated from proto/clarifai/api/image.proto</summary>
  public static partial class ImageReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/clarifai/api/image.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ImageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5wcm90by9jbGFyaWZhaS9hcGkvaW1hZ2UucHJvdG8SDGNsYXJpZmFpLmFw",
            "aSJPCgVJbWFnZRILCgN1cmwYASABKAkSDgoGYmFzZTY0GAIgASgMEgwKBGNy",
            "b3AYAyADKAISGwoTYWxsb3dfZHVwbGljYXRlX3VybBgEIAEoCEJaChtjbGFy",
            "aWZhaTIuaW50ZXJuYWwuZ3JwYy5hcGlaA2FwaaICBENBSVCqAhZDbGFyaWZh",
            "aS5JbnRlcm5hbC5HUlBDwgIBX8oCEUNsYXJpZmFpXEludGVybmFsYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Clarifai.Internal.GRPC.Image), global::Clarifai.Internal.GRPC.Image.Parser, new[]{ "Url", "Base64", "Crop", "AllowDuplicateUrl" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Image : pb::IMessage<Image> {
    private static readonly pb::MessageParser<Image> _parser = new pb::MessageParser<Image>(() => new Image());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Image> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Clarifai.Internal.GRPC.ImageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Image() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Image(Image other) : this() {
      url_ = other.url_;
      base64_ = other.base64_;
      crop_ = other.crop_.Clone();
      allowDuplicateUrl_ = other.allowDuplicateUrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Image Clone() {
      return new Image(this);
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 1;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "base64" field.</summary>
    public const int Base64FieldNumber = 2;
    private pb::ByteString base64_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Base64 {
      get { return base64_; }
      set {
        base64_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "crop" field.</summary>
    public const int CropFieldNumber = 3;
    private static readonly pb::FieldCodec<float> _repeated_crop_codec
        = pb::FieldCodec.ForFloat(26);
    private readonly pbc::RepeatedField<float> crop_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<float> Crop {
      get { return crop_; }
    }

    /// <summary>Field number for the "allow_duplicate_url" field.</summary>
    public const int AllowDuplicateUrlFieldNumber = 4;
    private bool allowDuplicateUrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AllowDuplicateUrl {
      get { return allowDuplicateUrl_; }
      set {
        allowDuplicateUrl_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Image);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Image other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Url != other.Url) return false;
      if (Base64 != other.Base64) return false;
      if(!crop_.Equals(other.crop_)) return false;
      if (AllowDuplicateUrl != other.AllowDuplicateUrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (Base64.Length != 0) hash ^= Base64.GetHashCode();
      hash ^= crop_.GetHashCode();
      if (AllowDuplicateUrl != false) hash ^= AllowDuplicateUrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Url.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Url);
      }
      if (Base64.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Base64);
      }
      crop_.WriteTo(output, _repeated_crop_codec);
      if (AllowDuplicateUrl != false) {
        output.WriteRawTag(32);
        output.WriteBool(AllowDuplicateUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (Base64.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Base64);
      }
      size += crop_.CalculateSize(_repeated_crop_codec);
      if (AllowDuplicateUrl != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Image other) {
      if (other == null) {
        return;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.Base64.Length != 0) {
        Base64 = other.Base64;
      }
      crop_.Add(other.crop_);
      if (other.AllowDuplicateUrl != false) {
        AllowDuplicateUrl = other.AllowDuplicateUrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Url = input.ReadString();
            break;
          }
          case 18: {
            Base64 = input.ReadBytes();
            break;
          }
          case 26:
          case 29: {
            crop_.AddEntriesFrom(input, _repeated_crop_codec);
            break;
          }
          case 32: {
            AllowDuplicateUrl = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
