// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/clarifai/api/usage_interval_type.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Clarifai.Internal.GRPC {

  /// <summary>Holder for reflection information generated from proto/clarifai/api/usage_interval_type.proto</summary>
  public static partial class UsageIntervalTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/clarifai/api/usage_interval_type.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UsageIntervalTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cixwcm90by9jbGFyaWZhaS9hcGkvdXNhZ2VfaW50ZXJ2YWxfdHlwZS5wcm90",
            "bxIMY2xhcmlmYWkuYXBpKjwKEVVzYWdlSW50ZXJ2YWxUeXBlEgkKBXVuZGVm",
            "EAASBwoDZGF5EAESCQoFbW9udGgQAhIICgR5ZWFyEANCWgobY2xhcmlmYWky",
            "LmludGVybmFsLmdycGMuYXBpWgNhcGmiAgRDQUlQqgIWQ2xhcmlmYWkuSW50",
            "ZXJuYWwuR1JQQ8ICAV/KAhFDbGFyaWZhaVxJbnRlcm5hbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Clarifai.Internal.GRPC.UsageIntervalType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum UsageIntervalType {
    [pbr::OriginalName("undef")] Undef = 0,
    [pbr::OriginalName("day")] Day = 1,
    [pbr::OriginalName("month")] Month = 2,
    [pbr::OriginalName("year")] Year = 3,
  }

  #endregion

}

#endregion Designer generated code
